apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - database.yaml
  - redis.yaml
  - firehol.yaml
  - api.yaml
  - cron.yaml
  - frontend.yaml
  - status.yaml
  - ingress.yaml
  - network-policy.yaml
secretGenerator:
  - name: gosmetch-secrets
    literals:
      - DUO_DB_USER=app
      - DUO_DB_PASS=CHANGE_ME
      - DUO_SMTP_USER=CHANGE_ME
      - DUO_SMTP_PASS=CHANGE_ME
      - DUO_R2_ACCT_ID=CHANGE_ME
      - DUO_R2_ACCESS_KEY_ID=CHANGE_ME
      - DUO_R2_ACCESS_KEY_SECRET=CHANGE_ME
      - DUO_VAPID_PRIVATE_KEY=CHANGE_ME
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/part-of: gosmetch
